### ISSUE TITLE
How do I set multiple global Python versions?

### ISSUE THREAD

**Issue by jacebrowning** [mloberg/puppet-python#21]
I'm looking for the equivalent of running:

```shell
$ pyenv global 3.4.3 2.7.8
```

-----

Adding:

```puppet
class { 'python::global':
  version => "3.4.3, 2.7.8"
}
```

causes:

```shell
Error: /opt/boxen/pyenv/bin/pyenv install --skip-existing 3.4.2, 2.7.8 returned 2 instead of one of [0]
```

**Comment by mloberg** [comment]
This is not supported at the moment as I was not aware you could do this with pyenv.

**Comment by jacebrowning** [comment]
I leaned of this yesterday. It provides a nice way to run Python 2-only and 3-only programs in the same shell.
